# Generated by Django 5.2.3 on 2025-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Product benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='Usage instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Active ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='precautions',
            field=models.TextField(blank=True, help_text='Precautions and warnings'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_info',
            field=models.TextField(blank=True, help_text='Safety information'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Possible side effects'),
        ),
        migrations.AddField(
            model_name='product',
            name='uses',
            field=models.TextField(blank=True, help_text='What is it used for'),
        ),
    ]
