# Generated by Django 5.2.3 on 2025-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20250731_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Doctor profile photo', null=True, upload_to='doctors/'),
        ),
    ]
