# Generated by Django 5.2.3 on 2025-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL to redirect when clicked (e.g., /products/ or https://example.com)', max_length=500),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.ImageField(blank=True, help_text='Banner image (optional)', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fas fa-shipping-fast)', max_length=50),
        ),
    ]
